[package]
name = "platform-ios"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
description = "iOS platform integration"

[dependencies]
shared = { path = "../../shared" }
ui = { path = "../../ui" }
parking_lot = { workspace = true }
tracing = { workspace = true }
